server:
  port: 13090
spring:
  application:
    name: eureka
  profiles:
    active: dev
---
spring:
  profiles: dev
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eurka: false
    fetch-registery: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/